{
 "title": "Cosmos monitoring for performance test",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "mongodb",
    "query": {}
   },
   {
    "name": "mongodbrg",
    "query": {}
   },
   {
    "name": "subscription",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Max Autoscaled RU for $mongodb by CollectionName where DatabaseName = 'idpay'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "{{CollectionName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       3600000,
       86400000
      ],
      "customNamespace": "Microsoft.DocumentDB/DatabaseAccounts",
      "dimensionFilters": [
       { "dimension": "DatabaseName", "filters": [ "idpay" ], "operator": "eq" },
       {
        "dimension": "CollectionName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "AutoscaledRU",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "region": "italynorth",
        "resourceGroup": "$mongodbrg",
        "resourceName": "$mongodb",
        "subscription": "4d177dd6-5c7d-40ab-8019-0c1be380a25d"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "4d177dd6-5c7d-40ab-8019-0c1be380a25d"
    }
   ]
  },
  {
   "title": "Max Normalized RU Consumption for $mongodb by Multiple Dimensions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "{{CollectionName}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       3600000,
       86400000
      ],
      "customNamespace": "Microsoft.DocumentDB/DatabaseAccounts",
      "dimensionFilters": [
       { "dimension": "DatabaseName", "filters": [ "idpay" ], "operator": "eq" },
       {
        "dimension": "CollectionName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "NormalizedRUConsumption",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "region": "italynorth",
        "resourceGroup": "$mongodbrg",
        "resourceName": "$mongodb",
        "subscription": "4d177dd6-5c7d-40ab-8019-0c1be380a25d"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "4d177dd6-5c7d-40ab-8019-0c1be380a25d"
    }
   ]
  },
  {
   "title": "Count Mongo Requests for $mongodb by Multiple Dimensions where DatabaseName = 'idpay'",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "{{CollectionName}} - {{CommandName}} - {{ErrorCode}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Microsoft.DocumentDB/DatabaseAccounts",
      "dimensionFilters": [
       { "dimension": "DatabaseName", "filters": [ "idpay" ], "operator": "eq" },
       {
        "dimension": "CollectionName",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "CommandName",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "ErrorCode",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "MongoRequests",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "microsoft.documentdb/databaseaccounts",
        "region": "italynorth",
        "resourceGroup": "$mongodbrg",
        "resourceName": "$mongodb",
        "subscription": "4d177dd6-5c7d-40ab-8019-0c1be380a25d"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "4d177dd6-5c7d-40ab-8019-0c1be380a25d"
    }
   ]
  },
  {
   "title": "Avg Mongo Request Charge for $mongodb by Multiple Dimensions where DatabaseName = 'idpay'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "{{CollectionName}} - {{CommandName}} - {{ErrorCode}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "Microsoft.DocumentDB/DatabaseAccounts",
      "dimensionFilters": [
       { "dimension": "DatabaseName", "filters": [ "idpay" ], "operator": "eq" },
       {
        "dimension": "CollectionName",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "CommandName",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "ErrorCode",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "MongoRequestCharge",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "region": "italynorth",
        "resourceGroup": "$mongodbrg",
        "resourceName": "$mongodb",
        "subscription": "4d177dd6-5c7d-40ab-8019-0c1be380a25d"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "4d177dd6-5c7d-40ab-8019-0c1be380a25d"
    }
   ]
  }
 ]
}