apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: idpay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.1.4
          args: ["start-dev"]
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-secret
                  key: admin-username
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: "admin"
            - name: KC_HOSTNAME
              value: "https://idpay.itn.internal.dev.cstar.pagopa.it/keycloak/"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_DB_URL_DATABASE
              value: "postgres"
            - name: KC_DB_URL_HOST
              value: "cstar-d-itn-idpay-keycloak.postgres.database.azure.com"
            - name: KC_DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  key: keycloak-config
                  name: data.kc-db-schema
              # value: "public"
            - name: KC_DB_URL_PORT
              valueFrom:
                configMapKeyRef:
                  key: keycloak-config
                  name: data.kc-db-url-port
              # value: "5432"
            - name: KC_DB
              valueFrom:
                configMapKeyRef:
                  key: keycloak-config
                  name: data.kc-db
            - name: KC_DB_USERNAME
              value: ""
            - name: KC_DB_PASSWORD
              value: ""
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            initialDelaySeconds: 120
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          resources:
            requests:
              memory: "756Mi"
              cpu: "200m"
            limits:
              memory: "1000Mi"
              cpu: "600m"
