{
 "title": "EIE",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Totale Prodotti Per Produttore",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "products\r\n| summarize Totale = count() by organizationName\r\n| order by organizationName ",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Produttori", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Prodotti Approvati per Produttore",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "products\r\n| where status == \"APPROVED\"\r\n| summarize Totale = count() by organizationName\r\n| order by organizationName asc\r\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Prodotti Da Controllare per Produttore",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "products\r\n| where status == \"SUPERVISED\"\r\n| summarize Totale = count() by organizationName\r\n| order by organizationName asc\r\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Prodotti Da Esaminare per Produttore",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "products\r\n| where status == \"UPLOADED\"\r\n| summarize Totale = count() by organizationName\r\n| order by organizationName asc\r\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Prodotti Rifiutati per Produttore",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "products\r\n| where status == \"REJECTED\"\r\n| summarize Totale = count() by organizationName\r\n| order by organizationName asc\r\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Prodotti Da Approvare per Produttore",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "products\r\n| where status == \"WAIT_APPROVED\"\r\n| summarize Totale = count() by organizationName\r\n| order by organizationName asc\r\n",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Prodotti", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Totale Prodotti Per Stato",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "products\r\n| summarize Totale = count() by status\r\n| order by status desc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Prodotti Per Categoria",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "products\r\n| summarize Totale = count() by category\r\n| order by category ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Prodotti Approvati Per Categoria",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "products\r\n| where status == 'APPROVED'\r\n| summarize Totale = count() by category\r\n| order by category ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Prodotti Rifiutati Per Categoria",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "products\r\n| where status == 'REJECTED'\r\n| summarize Totale = count() by category\r\n| order by category ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Prodotti Da Controllare Per Categoria",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "products\r\n| where status  == 'SUPERVISED'\r\n| summarize Totale = count() by category\r\n| order by category ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Prodotti Da Esaminare Per Categoria",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "products\r\n| where status  == 'UPLOADED'\r\n| summarize Totale = count() by category\r\n| order by category ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Prodotti Da Approvare Per Categoria",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "products\r\n| where status  == 'WAIT_APPROVED'\r\n| summarize Totale = count() by category\r\n| order by category ",
     "querySource": "raw"
    }
   ]
  }
 ]
}