{
 "title": "Quadrature",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "granularita", "label": "granularità", "query": "1m, 1h, 1d" },
   { "name": "initiativeId", "label": "Initiative ID", "query": "68dd003ccce8c534d1da22bc" },
   {
    "name": "month",
    "label": "Mese di riferimento",
    "query": {
     "query": "rewards_batch\n| summarize by month\n| where isnotempty(month)\n| sort by month desc"
    }
   },
   {
    "name": "serviceBus",
    "query": {}
   },
   {
    "name": "serviceBusRg",
    "query": {}
   },
   {
    "name": "subscription",
    "query": {}
   },
   {
    "name": "ds",
    "query": "grafana-azure-data-explorer-datasource"
   }
  ]
 },
 "panels": [
  { "title": "Riconciliazione dati", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transazioni valide che non hanno un wallet valido associato",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "query": "transaction\n| where status in (\"REWARDED\",\n      \"CAPTURED\",\n      \"INVOICED\",\n      \"AUTHORIZED\")\n| join kind=leftanti (wallet\n| where status == 'REFUNDABLE' and accruedCents > 0) on userId\n| summarize count()"
    }
   ]
  },
  {
   "title": "Wallet utilizzati ma ancora con budget residuo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "wallet \n| where status == 'REFUNDABLE' and accruedCents > 0 and amountCents > 0\n| summarize count()",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "onboarding con status anomalo rispetto ai wallet utilizzati",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "onboarding_citizen\n| join kind=inner (wallet\n| where status == 'REFUNDABLE' and accruedCents > 0\n) on userId\n| where status != 'ONBOARDING_OK'\n| summarize count()",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Lotti con numero trx disallineati",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let TxCountByBatch =\n    transaction\n    | where isnotempty(rewardBatchId)\n    | summarize tx_count = count() by rewardBatchId;\nrewards_batch\n| extend batch_id = tostring(_id),\n         expected_count = tolong(numberOfTransactions)\n| join kind=leftouter TxCountByBatch\n    on $left.batch_id == $right.rewardBatchId\n| extend tx_count = coalesce(tx_count, 0)\n| where expected_count != tx_count\n| count\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Wallet",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let non_assegnati = toscalar(\n    onboarding_citizen\n    | join kind=leftanti (wallet) on userId, initiativeId\n    | summarize count()\n);\nwallet\n| extend min_validita = datetime_diff('minute', datetime_add( 'second', 86399, voucherEndDate), now())\n| summarize \n  utilizzati = countif(status == 'REFUNDABLE' and accruedCents > 0), \n  attivi = countif(min_validita > 0 and status == 'REFUNDABLE' and amountCents > 0),\n  scaduti_stornati=countif(status == 'UNSUBSCRIBED'),\n  totali = count()\n| extend somma = utilizzati + attivi + scaduti_stornati\n| extend disallineati =totali - somma, non_assegnati\n| project-away somma\n",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Budget riservato multiplo di 100 euro",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "initiative_counters\n| where _id == strcat('{\"$oid\":\"', \"$initiativeId\", '\"}')\n| extend resto=reservedInitiativeBudgetCents%10000\n| project ismultiplo=iff(resto == 0, 'OK', 'KO')",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "N. Transazioni senza lotto",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "transaction\r\n| where isempty(rewardBatchId) and status in('INVOICED','REWARDED')\r\n| summarize cnt = count()\r\n| project cnt\r\n\r\n\r\n\r\n\r\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Discrepanza Voucher/Contatore Iniziativa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let total_rewards =\r\n    toscalar(\r\n        transaction\r\n        | where tostring(initiativeId) == \"68dd003ccce8c534d1da22bc\"\r\n        | where tostring(status) in (\"CAPTURED\", \"INVOICED\", \"REWARDED\")\r\n        | summarize sum(toint(rewardAccruedRewardCents))\r\n    );\r\ninitiative_counters\r\n| where _id == strcat('{\"$oid\":\"', \"$initiativeId\", '\"}')\r\n| project \r\n    result = (spentInitiativeBudgetCents - coalesce(total_rewards, 0)) / 100",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "N. Transazioni scomparse",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "transaction\r\n| where status == 'CAPTURED'\r\n| join kind=leftanti  (\r\n    transaction_in_progress\r\n) on $left._id == $right.id\r\n| summarize cnt = count()\r\n| project cnt\r\n\r\n\r\n\r\n\r\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "N. Cittadini disiscritti ma con preallocazione",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "onboarding_citizen\r\n| where status == 'UNSUBSCRIBED'\r\n| where isempty( familyId)\r\n| join kind=inner (initiative_counters) on $left.userId == $right.userId\r\n| summarize cnt = count()\r\n| project cnt\r\n\r\n\r\n\r\n\r\n",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Dettaglio lotti $month", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }, "repeat": "month" },
  {
   "title": "Check importi lotti autorizzati",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let TxByBatch =\r\n    transaction\r\n    | where isnotempty(rewardBatchId)\r\n      and status in ('INVOICED','REWARDED')\r\n      and rewardBatchTrxStatus == 'APPROVED'\r\n    | summarize\r\n        tx_sum_cents = tolong(sum(toint(rewardAccruedRewardCents))),\r\n        tx_count = count()\r\n      by rewardBatchId;\r\nlet toleranceCents = 0;\r\nlet monthToCheck = $month;\r\n// Confronta con la tabella rewards_batch\r\nrewards_batch\r\n| where month == monthToCheck and status == 'APPROVED'\r\n| extend\r\n    batch_id = tostring(_id),\r\n    approved_cents = tolong(coalesce(toint(approvedAmountCents), 0))\r\n| join kind=leftouter TxByBatch on $left.batch_id == $right.rewardBatchId\r\n| extend\r\n    tx_sum_cents = tolong(coalesce(tx_sum_cents, 0)),\r\n    tx_count = tolong(coalesce(tx_count, 0)),\r\n    delta_cents = approved_cents - tx_sum_cents\r\n| where abs(delta_cents) > toleranceCents  // seleziona solo i mismatch\r\n| project\r\n    rewardBatchId = _id,\r\n    approvedAmountCents = approved_cents,\r\n    tx_sum_cents,\r\n    delta_cents,\r\n    tx_count\r\n| count\r\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Lotti con suspendedAmount negativo",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "rewards_batch\r\n| where suspendedAmountCents < 0 and month == $month\r\n| summarize NumeroLottiErrati = count()",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Check lotti approvati senza filename",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "// Conteggio batch approvati senza filename per Stat Panel\r\nrewards_batch\r\n| where status == \"APPROVED\"\r\n| where isempty(filename) and month == $month\r\n| where numberOfTransactions > 0\r\n| count",
     "querySource": "raw"
    }
   ]
  }
 ]
}