{
 "title": "PariInitiativesInfra",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "query": "grafana-azure-data-explorer-datasource"
   },
   {
    "name": "initiativeId",
    "label": "Initiative ID",
    "query": {
     "query": "initiative_counters\n| where isnotempty(initiativeId)\n| extend initiativeValue = tostring(initiativeId)\n| distinct __text = initiativeValue, __value = initiativeValue\n| order by __text asc"
    }
   },
   {
    "name": "subscription",
    "query": {}
   },
   {
    "name": "idpayDataRg",
    "query": {}
   },
   {
    "name": "coreMonitorRg",
    "query": {}
   },
   {
    "name": "eventhubNs00",
    "query": {}
   },
   {
    "name": "eventhubNs01",
    "query": {}
   },
   {
    "name": "eventhubNsRdb",
    "query": {}
   },
   {
    "name": "bonusCdnProfile",
    "query": {}
   },
   {
    "name": "vnetRg",
    "query": {}
   },
   {
    "name": "apiRg",
    "query": {}
   },
   {
    "name": "idpayMonitoringRg",
    "query": {}
   },
   {
    "name": "coreAksRg",
    "query": {}
   },
   {
    "name": "aks",
    "query": {}
   },
   {
    "name": "applicationInsights",
    "query": {}
   },
   {
    "name": "appGateway",
    "query": {}
   },
   {
    "name": "apim",
    "query": {}
   },
   {
    "name": "idpayMongoDbAccount",
    "query": {}
   },
   {
    "name": "idpayRedis",
    "query": {}
   },
   {
    "name": "coreLaw",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "CDN Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TotalLatency",
      "metricNamespace": "microsoft.cdn/profiles",
      "region": "global",
      "resources": [
       {
        "metricNamespace": "Microsoft.Cdn/profiles",
        "region": "global",
        "resourceGroup": "$idpayDataRg",
        "resourceName": "$bonusCdnProfile",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "CDN Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "RequestCount",
      "metricNamespace": "microsoft.cdn/profiles",
      "region": "global",
      "resources": [
       {
        "metricNamespace": "Microsoft.Cdn/profiles",
        "region": "global",
        "resourceGroup": "$idpayDataRg",
        "resourceName": "$bonusCdnProfile",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 }, "options": { "content": "# PARI Initiatives\n" } },
  {
   "title": "App Gateway Request 1min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TotalRequests",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "region": "westeurope",
        "resourceGroup": "$vnetRg",
        "resourceName": "$appGateway",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "App Gateway New Connections per second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "/subscriptions/$subscription/resourceGroups/$coreMonitorRg/providers/Microsoft.OperationalInsights/workspaces/$coreLaw"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensions": [],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "NewConnectionsPerSecond",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resources": [
       { "resourceGroup": "$vnetRg", "resourceName": "$appGateway" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2640", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2641", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2642", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2643", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2644", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2645", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2646", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2647", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:2648", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     }
    }
   ]
  },
  {
   "title": "App Gateway Current Capacity Units",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "/subscriptions/$subscription/resourceGroups/$coreMonitorRg/providers/Microsoft.OperationalInsights/workspaces/$coreLaw"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensions": [],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "CapacityUnits",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resources": [
       { "resourceGroup": "$vnetRg", "resourceName": "$appGateway" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2864", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2865", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2866", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2867", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2868", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2869", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2870", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2871", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:2872", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     }
    }
   ]
  },
  {
   "title": "App Gateway Current Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "/subscriptions/$subscription/resourceGroups/$coreMonitorRg/providers/Microsoft.OperationalInsights/workspaces/$coreLaw"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensions": [],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "CurrentConnections",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resources": [
       { "resourceGroup": "$vnetRg", "resourceName": "$appGateway" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2449", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2450", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2451", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2452", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2453", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2454", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2455", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2456", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:2457", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     }
    }
   ]
  },
  {
   "title": "Application gateway total time",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MilliSeconds" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "/subscriptions/$subscription/resourceGroups/$coreMonitorRg/providers/Microsoft.OperationalInsights/workspaces/$coreLaw"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensions": [
       { "$$hashKey": "object:2984", "text": "None", "value": "None" },
       { "$$hashKey": "object:2985", "text": "Listener", "value": "Listener" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "ClientRtt",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resources": [
       { "resourceGroup": "$vnetRg", "resourceName": "$appGateway" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:2975", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:2976", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:2977", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:2978", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:2979", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:2980", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:2981", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:2982", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:2983", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     }
    },
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "/subscriptions/$subscription/resourceGroups/$coreMonitorRg/providers/Microsoft.OperationalInsights/workspaces/$coreLaw"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensions": [
       { "$$hashKey": "object:3239", "text": "None", "value": "None" },
       { "$$hashKey": "object:3240", "text": "Listener", "value": "Listener" },
       { "$$hashKey": "object:3241", "text": "Backend Server", "value": "BackendServer" },
       { "$$hashKey": "object:3242", "text": "Backend Pool", "value": "BackendPool" },
       { "$$hashKey": "object:3243", "text": "Backend Http Setting", "value": "BackendHttpSetting" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "BackendConnectTime",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resources": [
       { "resourceGroup": "$vnetRg", "resourceName": "$appGateway" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:3230", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:3231", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:3232", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:3233", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:3234", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:3235", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:3236", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:3237", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:3238", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     }
    },
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "/subscriptions/$subscription/resourceGroups/$coreMonitorRg/providers/Microsoft.OperationalInsights/workspaces/$coreLaw"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensions": [
       { "$$hashKey": "object:3279", "text": "None", "value": "None" },
       { "$$hashKey": "object:3280", "text": "Listener", "value": "Listener" },
       { "$$hashKey": "object:3281", "text": "Backend Server", "value": "BackendServer" },
       { "$$hashKey": "object:3282", "text": "Backend Pool", "value": "BackendPool" },
       { "$$hashKey": "object:3283", "text": "Backend Http Setting", "value": "BackendHttpSetting" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "BackendFirstByteResponseTime",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resources": [
       { "resourceGroup": "$vnetRg", "resourceName": "$appGateway" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:3270", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:3271", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:3272", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:3273", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:3274", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:3275", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:3276", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:3277", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:3278", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     }
    },
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "/subscriptions/$subscription/resourceGroups/$coreMonitorRg/providers/Microsoft.OperationalInsights/workspaces/$coreLaw"
     },
     "azureMonitor": {
      "aggOptions": [ "Average" ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensions": [
       { "$$hashKey": "object:3315", "text": "None", "value": "None" },
       { "$$hashKey": "object:3316", "text": "Listener", "value": "Listener" },
       { "$$hashKey": "object:3317", "text": "Backend Server", "value": "BackendServer" },
       { "$$hashKey": "object:3318", "text": "Backend Pool", "value": "BackendPool" },
       { "$$hashKey": "object:3319", "text": "Backend Http Setting", "value": "BackendHttpSetting" }
      ],
      "metricDefinition": "Microsoft.Network/applicationGateways",
      "metricName": "BackendLastByteResponseTime",
      "metricNamespace": "Microsoft.Network/applicationGateways",
      "resources": [
       { "resourceGroup": "$vnetRg", "resourceName": "$appGateway" }
      ],
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:3306", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:3307", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:3308", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:3309", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:3310", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:3311", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:3312", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:3313", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:3314", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     }
    }
   ]
  },
  {
   "title": "App Gateway Response code",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{dimensionvalue}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "HttpStatusGroup",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "ResponseStatus",
      "metricNamespace": "microsoft.network/applicationgateways",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/applicationGateways",
        "region": "westeurope",
        "resourceGroup": "$vnetRg",
        "resourceName": "$appGateway",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "APIM Request",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "microsoft.apimanagement/service",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.ApiManagement/service",
        "region": "westeurope",
        "resourceGroup": "$apiRg",
        "resourceName": "$apim",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "APIM Capacity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Capacity",
      "metricNamespace": "microsoft.apimanagement/service",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.ApiManagement/service",
        "region": "westeurope",
        "resourceGroup": "$apiRg",
        "resourceName": "$apim",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "API operation name",
   "type": "table",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "mode": "raw",
      "query": "\nlet dataset = requests\n| where $__timeFilter(timestamp)\n| where url has \"$initiativeId\"\n;\ndataset\n| summarize  Avg = avg(duration), 95Prc = percentile( duration,95), 99Prc = percentile( duration,99), Count = count()\n| project operation_Name=\"All\", Avg, 95Prc, 99Prc, Count\n| union(dataset\n| summarize  Avg = avg(duration), 95Prc = percentile( duration,95), 99Prc = percentile( duration,99), Count = count() by operation_Name\n| top 20 by Avg desc\n| order by Count\n)\n\n",
      "resources": [
       "/subscriptions/$subscription/resourceGroups/$idpayMonitoringRg/providers/Microsoft.Insights/components/$applicationInsights"
      ],
      "resultFormat": "logs"
     }
    }
   ]
  },
  {
   "title": "APIM Backend Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "BackendDuration",
      "metricNamespace": "microsoft.apimanagement/service",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.ApiManagement/service",
        "region": "westeurope",
        "resourceGroup": "$apiRg",
        "resourceName": "$apim",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "MongoDB RU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "{{dimensionvalue}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       3600000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "DatabaseName",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "NormalizedRUConsumption",
      "metricNamespace": "microsoft.documentdb/databaseaccounts",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "region": "italynorth",
        "resourceGroup": "$idpayDataRg",
        "resourceName": "$idpayMongoDbAccount",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Redis Connected client",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "connectedclients",
      "metricNamespace": "microsoft.cache/redisenterprise",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.Cache/redisEnterprise",
        "region": "italynorth",
        "resourceGroup": "$idpayDataRg",
        "resourceName": "$idpayRedis",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Redis Used Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "usedmemorypercentage",
      "metricNamespace": "microsoft.cache/redisenterprise",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.Cache/redisEnterprise",
        "region": "italynorth",
        "resourceGroup": "$idpayDataRg",
        "resourceName": "$idpayRedis",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Redis CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "percentProcessorTime",
      "metricNamespace": "microsoft.cache/redisenterprise",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.Cache/redisEnterprise",
        "region": "italynorth",
        "resourceGroup": "$idpayDataRg",
        "resourceName": "$idpayRedis",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Redis Key number",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "totalkeys",
      "metricNamespace": "microsoft.cache/redisenterprise",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.Cache/redisEnterprise",
        "region": "italynorth",
        "resourceGroup": "$idpayDataRg",
        "resourceName": "$idpayRedis",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Redis Miss rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "cachemisses",
      "metricNamespace": "microsoft.cache/redisenterprise",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.Cache/redisEnterprise",
        "region": "italynorth",
        "resourceGroup": "$idpayDataRg",
        "resourceName": "$idpayRedis",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Idpay Pod by Phase",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{phase}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       { "dimension": "namespace", "filters": [ "idpay" ], "operator": "eq" },
       {
        "dimension": "phase",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "kube_pod_status_phase",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "italynorth",
        "resourceGroup": "$coreAksRg",
        "resourceName": "$aks",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Idpay Nodepool CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       { "dimension": "nodepool", "filters": [ "csdgrenidpay" ], "operator": "eq" }
      ],
      "metricName": "node_cpu_usage_percentage",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "italynorth",
        "resourceGroup": "$coreAksRg",
        "resourceName": "$aks",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Idpay Nodepool MEM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       { "dimension": "nodepool", "filters": [ "csdgrenidpay" ], "operator": "eq" }
      ],
      "metricName": "node_memory_working_set_percentage",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "italynorth",
        "resourceGroup": "$coreAksRg",
        "resourceName": "$aks",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Keycloak Pod by Phase",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{phase}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       { "dimension": "namespace", "filters": [ "keycloak" ], "operator": "eq" },
       {
        "dimension": "phase",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "kube_pod_status_phase",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "italynorth",
        "resourceGroup": "$coreAksRg",
        "resourceName": "$aks",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Keycloak Nodepool CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       { "dimension": "nodepool", "filters": [ "usrkeycloak" ], "operator": "eq" }
      ],
      "metricName": "node_cpu_usage_percentage",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "italynorth",
        "resourceGroup": "$coreAksRg",
        "resourceName": "$aks",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Keycloak Nodepool MEM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       { "dimension": "nodepool", "filters": [ "usrkeycloak" ], "operator": "eq" }
      ],
      "metricName": "node_memory_working_set_percentage",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.ContainerService/managedClusters",
        "region": "italynorth",
        "resourceGroup": "$coreAksRg",
        "resourceName": "$aks",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Idpay POD Cpu Info (Current)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "KubePodInventory\n| where TimeGenerated > ago(2m)\n| where ClusterName == \"$aks\"\n| where Namespace == \"idpay\"\n| summarize arg_max(TimeGenerated, *) by ContainerName\n| project Name, ContainerName\n| join kind = inner (\n    Perf\n    | where TimeGenerated > ago(2m)\n    | where ObjectName == 'K8SContainer'\n    | where CounterName == 'cpuLimitNanoCores'\n    | where InstanceName contains '$aks'\n    | extend ContainerNameParts = split(InstanceName, '/')\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\n    | summarize arg_max(TimeGenerated, *) by ContainerName\n    | project ContainerName, CpuLimit=CounterValue\n    | join kind = inner (\n        Perf\n        | where TimeGenerated > ago(2m)\n        | where ObjectName == 'K8SContainer'\n        | where CounterName == 'cpuUsageNanoCores'\n        | where InstanceName contains '$aks'\n        | extend ContainerNameParts = split(InstanceName, '/')\n        | extend ContainerNamePartCount = array_length(ContainerNameParts)            \n        | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \n        | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\n        | summarize arg_max(TimeGenerated, *) by ContainerName\n        | project TimeGenerated, ContainerName, CpuUsage=CounterValue\n    ) on ContainerName\n) on ContainerName\n| order by Name asc\n| project Name, CpuLimit=(CpuLimit / 1000000), CpuUsage=(CpuUsage / 1000000)",
      "resources": [
       "/subscriptions/$subscription/resourceGroups/$coreMonitorRg/providers/Microsoft.OperationalInsights/workspaces/$coreLaw"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resources": [
       { "resourceGroup": "select", "resourceName": "select" }
      ],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     }
    }
   ]
  },
  {
   "title": "Keycloack POD Cpu Info (Current)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "KubePodInventory\n| where TimeGenerated > ago(2m)\n| where ClusterName == \"$aks\"\n| where Namespace == \"keycloak\"\n| summarize arg_max(TimeGenerated, *) by ContainerName\n| project Name, ContainerName\n| join kind = inner (\n    Perf\n    | where TimeGenerated > ago(2m)\n    | where ObjectName == 'K8SContainer'\n    | where CounterName == 'cpuLimitNanoCores'\n    | where InstanceName contains '$aks'\n    | extend ContainerNameParts = split(InstanceName, '/')\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\n    | summarize arg_max(TimeGenerated, *) by ContainerName\n    | project ContainerName, CpuLimit=CounterValue\n    | join kind = inner (\n        Perf\n        | where TimeGenerated > ago(2m)\n        | where ObjectName == 'K8SContainer'\n        | where CounterName == 'cpuUsageNanoCores'\n        | where InstanceName contains '$aks'\n        | extend ContainerNameParts = split(InstanceName, '/')\n        | extend ContainerNamePartCount = array_length(ContainerNameParts)            \n        | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \n        | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\n        | summarize arg_max(TimeGenerated, *) by ContainerName\n        | project TimeGenerated, ContainerName, CpuUsage=CounterValue\n    ) on ContainerName\n) on ContainerName\n| order by Name asc\n| project Name, CpuLimit=(CpuLimit / 1000000), CpuUsage=(CpuUsage / 1000000)",
      "resources": [
       "/subscriptions/$subscription/resourceGroups/$coreMonitorRg/providers/Microsoft.OperationalInsights/workspaces/$coreLaw"
      ],
      "resultFormat": "table"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "metricDefinition": "select",
      "metricName": "select",
      "metricNamespace": "select",
      "resources": [
       { "resourceGroup": "select", "resourceName": "select" }
      ],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     }
    }
   ]
  },
  { "title": "EventHub Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Event Hub 00 Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "EntityName", "filters": [ "idpay-transaction" ], "operator": "eq" }
      ],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "italynorth",
        "resourceGroup": "$idpayDataRg",
        "resourceName": "$eventhubNs00",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Event Hub 00 Outgoing Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "EntityName", "filters": [ "idpay-transaction" ], "operator": "eq" }
      ],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "italynorth",
        "resourceGroup": "$idpayDataRg",
        "resourceName": "$eventhubNs00",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Event Hub 01 Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [
         "idpay-errors",
         "idpay-commands",
         "idpay-reward-notification-storage-events",
         "idpay-timeline",
         "idpay-rule-update"
        ],
        "operator": "eq"
       }
      ],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "italynorth",
        "resourceGroup": "$idpayDataRg",
        "resourceName": "$eventhubNs01",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Event Hub 01 Outgoing Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [
         "idpay-errors",
         "idpay-commands",
         "idpay-timeline",
         "idpay-reward-notification-storage-events",
         "idpay-rule-update"
        ],
        "operator": "eq"
       }
      ],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "italynorth",
        "resourceGroup": "$idpayDataRg",
        "resourceName": "$eventhubNs01",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  { "title": "RDB Topic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "RDB Topic Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [
         "idpay-asset-register",
         "idpay-asset-register_topic"
        ],
        "operator": "eq"
       }
      ],
      "metricName": "IncomingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "italynorth",
        "resourceGroup": "$idpayDataRg",
        "resourceName": "$eventhubNsRdb",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "RDB Topic Outgoing Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [
         "idpay-asset-register",
         "idpay-asset-register_topic"
        ],
        "operator": "eq"
       }
      ],
      "metricName": "OutgoingMessages",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "italynorth",
        "resourceGroup": "$idpayDataRg",
        "resourceName": "$eventhubNsRdb",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "RDB Topic Errors and Throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [
         "idpay-asset-register",
         "idpay-asset-register_topic"
        ],
        "operator": "eq"
       }
      ],
      "metricName": "ThrottledRequests",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "italynorth",
        "resourceGroup": "$idpayDataRg",
        "resourceName": "$eventhubNsRdb",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [
         "idpay-asset-register",
         "idpay-asset-register_topic"
        ],
        "operator": "eq"
       }
      ],
      "metricName": "UserErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "italynorth",
        "resourceGroup": "$idpayDataRg",
        "resourceName": "$eventhubNsRdb",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "EntityName",
        "filters": [
         "idpay-asset-register",
         "idpay-asset-register_topic"
        ],
        "operator": "eq"
       }
      ],
      "metricName": "ServerErrors",
      "metricNamespace": "microsoft.eventhub/namespaces",
      "region": "italynorth",
      "resources": [
       {
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "region": "italynorth",
        "resourceGroup": "$idpayDataRg",
        "resourceName": "$eventhubNsRdb",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  }
 ]
}