{
 "title": "Monitoraggio MDC",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "query": "grafana-azure-data-explorer-datasource"
   }
  ]
 },
 "panels": [
  { "title": "Messaggi da SEND", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dati aggiornati al",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "mdc",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "MessageVolumeSnapshot\r\n| summarize LastWindowStart = max(todatetime(window_start))\r\n| extend ['Ultimo aggiornamento'] = LastWindowStart + 15m\r\n| project ['Ultimo aggiornamento']",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Messaggi con e senza pagamenti",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "mdc",
     "expression": {
      "columns": {
       "columns": [
        "sent_with_payment",
        "sent_without_payment",
        "discarded_with_payment",
        "discarded_without_payment"
       ],
       "type": "property"
      },
      "from": { "property": { "name": "MessageVolumeSnapshot", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "MessageVolumeSnapshot\n| where $__timeFilter(window_start)\n| summarize \n    ['Accettati con pagamento']    = coalesce(sum(sent_with_payment), 0),\n    ['Accettati senza pagamento']  =  coalesce(sum(sent_without_payment), 0),\n    ['Scartati con pagamento']   =  coalesce(sum(discarded_with_payment), 0),\n    ['Scartati senza pagamento'] =  coalesce(sum(discarded_without_payment), 0)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Messaggi accettati",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "mdc",
     "expression": {
      "columns": {
       "columns": [
        "message_sent_count",
        "message_discarded_count"
       ],
       "type": "property"
      },
      "from": { "property": { "name": "MessageVolumeSnapshot", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "MessageVolumeSnapshot\n| where $__timeFilter(window_start)\n| summarize ['Messaggi accettati'] = coalesce(sum(message_sent_count), 0)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Messaggi scartati",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "mdc",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "MessageVolumeSnapshot\r\n| where $__timeFilter(window_start)\r\n| summarize ['Messaggi scartati'] = coalesce(sum(message_discarded_count), 0)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Accettati e scartati nel tempo",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "mdc",
     "expression": {
      "columns": {
       "columns": [
        "window_start",
        "message_sent_count",
        "message_discarded_count"
       ],
       "type": "property"
      },
      "from": { "property": { "name": "MessageVolumeSnapshot", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "MessageVolumeSnapshot\n| project window_start, \n          ['Messaggi accettati'] = message_sent_count, \n          ['Messaggi scartati'] = message_discarded_count\n| where $__timeFilter(window_start)\n| order by window_start asc",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Consensi cittadini", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Cittadini inattivi ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "mdc",
     "expression": {
      "columns": { "columns": [ "citizens_inactive" ], "type": "property" },
      "from": { "property": { "name": "CitizenMetricsAggregate", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CitizenMetricsSnapshot\n| extend consents_dynamic = todynamic(consents)\n| extend consent_keys = bag_keys(consents_dynamic)\n| mv-expand key = consent_keys to typeof(string)\n| extend consent_obj = consents_dynamic[key]\n| extend tppState = tobool(consent_obj[\"tppState\"])\n| extend tcDate_ms = tolong(consent_obj[\"tcDate\"][\"$date\"])\n| extend tppDate = datetime(1970-01-01) + totimespan(tcDate_ms * 1ms)\n| where $__timeFilter(tppDate)\n| summarize has_any_true = countif(tppState == true) by fiscal_code\n| summarize ['Cittadini senza consenso'] = countif(has_any_true == 0)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Cittadini attivi",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "mdc",
     "expression": {
      "from": { "property": { "name": "CitizenMetricsSnapshot", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CitizenMetricsSnapshot\r\n| extend consents_dynamic = todynamic(consents)\r\n| extend consent_keys = bag_keys(consents_dynamic)\r\n| mv-expand key = consent_keys to typeof(string)\r\n| extend consent_obj = consents_dynamic[key]\r\n| extend tppState = tobool(consent_obj[\"tppState\"])\r\n| extend tcDate_ms = tolong(consent_obj[\"tcDate\"][\"$date\"])\r\n| extend tppDate = datetime(1970-01-01) + totimespan(tcDate_ms * 1ms)\r\n| where $__timeFilter(tppDate)\r\n| summarize has_any_true = countif(tppState == true) by fiscal_code\r\n| summarize ['Cittadini con consenso'] = countif(has_any_true >= 1)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Stato cittadini nel tempo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 22 },
   "targets": [
    {
     "database": "mdc",
     "expression": {
      "from": { "property": { "name": "CitizenMetricsSnapshot", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "CitizenMetricsSnapshot\r\n| extend consents_dynamic = todynamic(consents)\r\n| extend consent_keys = bag_keys(consents_dynamic)\r\n| mv-expand key = consent_keys to typeof(string)\r\n| extend consent_obj = consents_dynamic[key]\r\n| extend tppState = tobool(consent_obj[\"tppState\"])\r\n| extend tcDate = unixtime_milliseconds_todatetime(tolong(consent_obj[\"tcDate\"][\"$date\"]))\r\n| where tcDate >= $__timeFrom and tcDate <= $__timeTo  // Va in base alla data deffinita da grafana\r\n| summarize \r\n    has_any_true    = countif(tppState == true),\r\n    last_true_date  = maxif(tcDate, tppState == true),\r\n    last_false_date = maxif(tcDate, tppState == false)\r\n  by fiscal_code\r\n| extend stato = iff(has_any_true > 0, \"Attivi\", \"Inattivi\")\r\n| extend relevant_date = iff(stato == \"Attivi\", last_true_date, last_false_date)\r\n| summarize \r\n    Attivi    = dcountif(fiscal_code, stato == \"Attivi\"),\r\n    NonAttivi = dcountif(fiscal_code, stato == \"Inattivi\")\r\n  by bin(relevant_date, 1d)\r\n| order by relevant_date asc",
     "querySource": "raw"
    }
   ]
  }
 ]
}