{
 "title": "ESE",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "query": "grafana-azure-data-explorer-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "Numero Transazioni Per Franchise",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "merchant_initiative_counters\r\n| where initiativeId == \"69e0fa95e21efa516c7b8dec\"\r\n| join kind=leftouter (\r\n    merchant\r\n    | project businessName, _id\r\n) on $left.merchantId == $right._id\r\n| project businessName,trxNumber\r\n| order by businessName desc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Numero Transazioni Per Tipologia Punto Vendita",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "transaction\r\n| where rewardInitiatieveId == \"69e0fa95e21efa516c7b8dec\"\r\n| join kind=rightouter (\r\n    point_of_sales\r\n    | project _id, type\r\n) on $left.pointOfSaleId == $right._id\r\n| summarize TotaleTransazioni = count() by type",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Numero Transazioni Per Tipologia Voucher",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "transaction\r\n| where rewardInitiatieveId == \"69e0fa95e21efa516c7b8dec\"\r\n| where status in ( 'INVOICED', 'CAPTURED')\r\n| extend LungaDurata = (trxChargeDate - trxDate) > 15m\r\n| summarize TransazioniCount = count() by LungaDurata\r\n| extend Category = iff(LungaDurata, \"Voucher statico\", \"Voucher app\")\r\n| project Category, TransazioniCount\r\n",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Numero Rimborsi Per Franchise",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "merchant_initiative_counters\r\n| where initiativeId == \"69e0fa95e21efa516c7b8dec\"\r\n| join kind=leftouter (\r\n    merchant\r\n    | project businessName, _id\r\n) on $left.merchantId == $right._id\r\n| project businessName, refoundNumber\r\n| order by businessName desc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Punti Vendita Per Regione",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "point_of_sales\r\n| join kind=inner (\r\n    point_of_sales_initiative\r\n    | where initiativeId == \"69e0fa95e21efa516c7b8dec\"\r\n    | project pointOfSaleId\r\n) on $left._id == $right.pointOfSaleId\r\n| summarize Totale = count() by region\r\n| order by Totale desc ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Punti Vendita Per Esercenti",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "database": "idpay",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "merchant\r\n| join kind=rightouter  (\r\n    point_of_sales\r\n    | join kind=inner (\r\n        point_of_sales_initiative\r\n        | where initiativeId == \"69e0fa95e21efa516c7b8dec\"\r\n        | project pointOfSaleId\r\n    ) on $left._id == $right.pointOfSaleId\r\n) on $left._id == $right.merchantId\r\n| summarize Totale = count() by businessName\r\n| order by Totale desc \r\n| limit 10",
     "querySource": "raw"
    }
   ]
  }
 ]
}