.set-or-replace initiative_export_configuration <|
datatable(initiativeId:string, exportConfiguration:dynamic)
[
  "bonusdecoder", dynamic({
    "fields": ["gtinCode", "model", "brand", "productName", "category", "productCode"],
    "headers": {
      "gtinCode": "GTIN",
      "model": "Modello",
      "brand": "Marca",
      "productName": "Nome del prodotto",
      "category": "Categoria",
      "productCode": "Codice prodotto"
    }
  }),
  "bonuselettrodomestici", dynamic({
    "fields": ["gtinCode", "model", "brand", "eprelCode", "countryOfProduction", "energyClass", "capacity", "productName", "category", "productGroup", "productCode"],
    "headers": {
      "gtinCode": "GTIN",
      "model": "Modello",
      "brand": "Marca",
      "eprelCode": "Codice Eprel",
      "countryOfProduction": "Paese di Produzione",
      "energyClass": "Classe Energetica",
      "capacity": "Capacita",
      "productName": "Nome del prodotto",
      "category": "Categoria",
      "productGroup": "Gruppo prodotto",
      "productCode": "Codice prodotto"
    }
  })
];

.set-or-replace category_translation <|
datatable(initiativeId:string, categoryCode:string, language:string, description:string)
[
  "bonusdecoder", "DS", "it", "Satellitare",
  "bonusdecoder", "DT", "it", "Terrestre",
  "bonusdecoder", "DTS", "it", "Terrestre e Satellitare",
  "bonusdecoder", "DTC", "it", "Terrestre via Cavo",
  "bonusdecoder", "DTSC", "it", "Terrestre, Satellitare e via Cavo",
  "bonuselettrodomestici", "WASHINGMACHINES", "it", "Lavatrice",
  "bonuselettrodomestici", "WASHERDRIERS", "it", "Lavasciuga",
  "bonuselettrodomestici", "OVENS", "it", "Forno",
  "bonuselettrodomestici", "RANGEHOODS", "it", "Cappa da cucina",
  "bonuselettrodomestici", "DISHWASHERS", "it", "Lavastoviglie",
  "bonuselettrodomestici", "TUMBLEDRYERS", "it", "Asciugatrice",
  "bonuselettrodomestici", "REFRIGERATINGAPPL", "it", "Apparecchio di refrigerazione",
  "bonuselettrodomestici", "COOKINGHOBS", "it", "Piano cottura"
];
