env           = "dev"
cicd_kv_name  = "cstar-d-itn-cicd-kv"
cicd_kv_rg    = "cstar-d-itn-core-sec-rg"
idpay_kv_name = "cstar-d-itn-idpay-kv"
idpay_kv_rg   = "cstar-d-itn-idpay-security-rg"
functional_testing_secret_name = "pari_feature_secrets.yaml"
