variable "prefix" {
  type = string
  validation {
    condition = (
      length(var.prefix) <= 6
    )
    error_message = "Max length is 6 chars."
  }
}

variable "env" {
  type        = string
  description = "Environment"
}

variable "env_short" {
  type = string
  validation {
    condition = (
      length(var.env_short) <= 1
    )
    error_message = "Max length is 1 chars."
  }
}

variable "location" {
  type = string
}

variable "location_short" {
  type        = string
  description = "Location short like eg: neu, weu.."
}

variable "location_display_name" {
  type        = string
  description = "Location short like eg: neu, weu.."
}

variable "tags" {
  type = map(any)
  default = {
    CreatedBy = "Terraform"
  }
}

variable "domain" {
  type = string
  validation {
    condition = (
      length(var.domain) <= 12
    )
    error_message = "Max length is 12 chars."
  }
}

#
# Networking
#
variable "cidr_subnet_synthetic_cae" {
  type        = list(string)
  description = "Address prefixes subnet synthetic"
}

variable "cidr_subnet_storage_private_endpoints" {
  type        = list(string)
  description = "Address prefixes subnet for storage private endpoints"
}

variable "cidr_subnet_container_app_private_endpoints" {
  type        = list(string)
  description = "Address prefixes subnet for container app private endpoints"
}

#
# Monitoring
#
variable "monitoring_law_sku" {
  type        = string
  description = "Sku of the Log Analytics Workspace"
}

variable "monitoring_law_retention_in_days" {
  type        = number
  description = "The workspace data retention in days"
}

variable "monitoring_law_daily_quota_gb" {
  type        = number
  description = "The workspace daily quota for ingestion in GB."
}

## Synthetic Monitoring

variable "synthetic_storage_account_replication_type" {
  type        = string
  description = "(Required) table storage replication type"
}

variable "synthetic_self_alert_enabled" {
  type        = bool
  description = "(Optional) enables the alert on the function itself"
  default     = true
}

variable "synthetic_alerts_enabled" {
  type        = bool
  description = "(Optional) Enables alerts generated by the synthetic monitoring probe"
}

variable "synthetic_domain_tae_enabled" {
    type        = bool
    description = "(Optional) Enables the synthetic monitoring for the RTD"
}

variable "synthetic_domain_idpay_enabled" {
    type        = bool
    description = "(Optional) Enables the synthetic monitoring for the Idpay"
}

variable "synthetic_domain_mc_enabled" {
    type        = bool
    description = "(Optional) Enables the synthetic monitoring for the Idpay"
}

variable "synthetic_domain_shared_enabled" {
    type        = bool
    description = "(Optional) Enables the synthetic monitoring for the Idpay"
}
