name: 🔍 Static Analysis MA

on:
  push:
    branches:
      - main
      - fix-main-static-analysis

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    env:
      TF_PLUGIN_CACHE_DIR: /tmp/.terraform.d/plugin-cache

    steps:
      - name: ⚡ Checkout code
        uses: actions/checkout@v4.1.1

      - name: 📖 Read Terraform version
        run: |
          echo "TERRAFORM_VERSION=$(cat .terraform-version)" >> $GITHUB_ENV

      - name: 🔨 Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.0
        with:
          terraform_version: "${{ env.TERRAFORM_VERSION }}"

      - name: 🧹 Clean provider directories
        run: |
          find . -type d -name ".terraform" -exec rm -rf {} +
          find . -type f -name ".terraform.lock.hcl" -exec rm -f {} +
          rm -rf $TF_PLUGIN_CACHE_DIR/*

      - name: 💾 Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: $TF_PLUGIN_CACHE_DIR
          key: ${{ runner.os }}-terraform-${{ env.TERRAFORM_VERSION }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terraform-${{ env.TERRAFORM_VERSION }}-
            ${{ runner.os }}-terraform-

      - name: 🔧 Setup Terraform plugin cache
        run: |
          mkdir -p $TF_PLUGIN_CACHE_DIR
          echo 'plugin_cache_dir = "/tmp/.terraform.d/plugin-cache"' > ~/.terraformrc

      - name: 🏁 Init Terraform folders
        shell: bash
        run: |
          echo "📢 Show space"
          df -h

          echo -e "\n+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-"
          echo    "+ 🏁 INIT TERRAFORM FOLDERS 🏁   +"
          echo -e "+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-\n"

          FOLDERS=$(grep -rl --include='*.tf' --exclude-dir='.terraform' '^' . | xargs -I{} dirname {} | sort -u)
          echo "FOLDERS=${FOLDERS}"

          for f in $FOLDERS; do
            echo -e "\nProcessing: ${f}"
            (
              cd "${f}" || exit
              sed -i -e 's/  backend "azurerm" {}//g' 99_main.tf
              terraform init -upgrade
            )
          done

      - name: Show precommit version
        shell: bash
        run: |
          echo -e "\n+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+"
          echo    "+ 1️⃣  SHOW PRECOMMIT VERSION 1️⃣  +"
          echo -e "+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+\n"

          TAG=v1.96.2@sha256:01f870b7689b5a09c1a370914fcddcac42c4b6478c9d369e1d2590dd0a66ffd0
          docker run --rm --entrypoint cat ghcr.io/antonbabenko/pre-commit-terraform:$TAG /usr/bin/tools_versions_info

      - name: 🚨 Run precommit
        shell: bash
        run: |
          echo -e "\n+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+"
          echo    "+- 🚨 PRECOMMIT TERRAFORM 🚨 -+"
          echo -e "+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+\n"

          TAG=v1.96.2@sha256:01f870b7689b5a09c1a370914fcddcac42c4b6478c9d369e1d2590dd0a66ffd0
          docker run \
            -v "$(pwd)":/lint \
            -v $TF_PLUGIN_CACHE_DIR:/tmp/.terraform.d/plugin-cache \
            -w /lint \
            ghcr.io/antonbabenko/pre-commit-terraform:$TAG \
            run -a
